<a href="https://colab.research.google.com/github/kevinmoreno1-ux/ENTREGAS/blob/main/01-exploraci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Specify the path to your CSV file in Google Drive
# Replace 'MyDrive/your_folder/your_file.csv' with your actual path
file_path = '/content/drive/MyDrive/IA/train.csv'

# Read the CSV file into a Pandas DataFrame
data = pd.read_csv(file_path)



# Mostrar las primeras filas del archivo
print("Primeras filas del dataset:")
print(data.head())

print("\nInformación general del dataset:")
print(data.info())

print("\nColumnas disponibles:")
print(data.columns)

# Ejemplo 1: Cantidad de estudiantes por clase
if 'class' in data.columns:
    print("\nCantidad de estudiantes por clase:")
    print(data['class'].value_counts())

# Ejemplo 2: Cantidad de estudiantes por localidad
if 'localidad' in data.columns or 'location' in data.columns:
    columna_localidad = 'localidad' if 'localidad' in data.columns else 'location'
    print(f"\nCantidad de estudiantes por {columna_localidad}:")
    print(data[columna_localidad].value_counts())

# Ejemplo 3: Cantidad de estudiantes por combinación Clase - Localidad
if 'class' in data.columns and (('localidad' in data.columns) or ('location' in data.columns)):
    columna_localidad = 'localidad' if 'localidad' in data.columns else 'location'
    print(f"\nCantidad de estudiantes por clase y {columna_localidad}:")
    print(data.groupby(['class', columna_localidad]).size())

# Estadísticas generales
print("\nResumen estadístico:")
print(data.describe(include='all'))

Mounted at /content/drive
Primeras filas del dataset:
       ID  PERIODO_ACADEMICO            E_PRGM_ACADEMICO E_PRGM_DEPARTAMENTO  \
0  904256              20212                  ENFERMERIA              BOGOTÁ
1  645256              20212                     DERECHO           ATLANTICO
2  308367              20203       MERCADEO Y PUBLICIDAD              BOGOTÁ
3  470353              20195  ADMINISTRACION DE EMPRESAS           SANTANDER
4  989032              20212                  PSICOLOGIA           ANTIOQUIA

                E_VALORMATRICULAUNIVERSIDAD E_HORASSEMANATRABAJA  \
0  Entre 5.5 millones y menos de 7 millones    Menos de 10 horas
1  Entre 2.5 millones y menos de 4 millones                    0
2  Entre 2.5 millones y menos de 4 millones      Más de 30 horas
3  Entre 4 millones y menos de 5.5 millones                    0
4  Entre 2.5 millones y menos de 4 millones  Entre 21 y 30 horas

  F_ESTRATOVIVIENDA F_TIENEINTERNET                    F_EDUCACIONPADRE  \
0         Estrato 3              Si    Técnica o tecnológica incompleta
1         Estrato 3              No      Técnica o tecnológica completa
2         Estrato 3              Si  Secundaria (Bachillerato) completa
3         Estrato 4              Si                             No sabe
4         Estrato 3              Si                   Primaria completa

  F_TIENELAVADORA  ... E_PRIVADO_LIBERTAD E_PAGOMATRICULAPROPIO  \
0              Si  ...                  N                    No
1              Si  ...                  N                    No
2              Si  ...                  N                    No
3              Si  ...                  N                    No
4              Si  ...                  N                    No

  F_TIENECOMPUTADOR F_TIENEINTERNET.1                    F_EDUCACIONMADRE  \
0                Si                Si                           Postgrado
1                Si                No    Técnica o tecnológica incompleta
2                No                Si  Secundaria (Bachillerato) completa
3                Si                Si  Secundaria (Bachillerato) completa
4                Si                Si                   Primaria completa

  RENDIMIENTO_GLOBAL INDICADOR_1  INDICADOR_2  INDICADOR_3  INDICADOR_4
0         medio-alto       0.322        0.208        0.310        0.267
1               bajo       0.311        0.215        0.292        0.264
2               bajo       0.297        0.214        0.305        0.264
3               alto       0.485        0.172        0.252        0.190
4         medio-bajo       0.316        0.232        0.285        0.294

[5 rows x 21 columns]

Información general del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 21 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ID                           692500 non-null  int64
 1   PERIODO_ACADEMICO            692500 non-null  int64
 2   E_PRGM_ACADEMICO             692500 non-null  object
 3   E_PRGM_DEPARTAMENTO          692500 non-null  object
 4   E_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   E_HORASSEMANATRABAJA         661643 non-null  object
 6   F_ESTRATOVIVIENDA            660363 non-null  object
 7   F_TIENEINTERNET              665871 non-null  object
 8   F_EDUCACIONPADRE             669322 non-null  object
 9   F_TIENELAVADORA              652727 non-null  object
 10  F_TIENEAUTOMOVIL             648877 non-null  object
 11  E_PRIVADO_LIBERTAD           692500 non-null  object
 12  E_PAGOMATRICULAPROPIO        686002 non-null  object
 13  F_TIENECOMPUTADOR            654397 non-null  object
 14  F_TIENEINTERNET.1            665871 non-null  object
 15  F_EDUCACIONMADRE             668836 non-null  object
 16  RENDIMIENTO_GLOBAL           692500 non-null  object
 17  INDICADOR_1                  692500 non-null  float64
 18  INDICADOR_2                  692500 non-null  float64
 19  INDICADOR_3                  692500 non-null  float64
 20  INDICADOR_4                  692500 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 111.0+ MB
None

Columnas disponibles:
Index(['ID', 'PERIODO_ACADEMICO', 'E_PRGM_ACADEMICO', 'E_PRGM_DEPARTAMENTO',
       'E_VALORMATRICULAUNIVERSIDAD', 'E_HORASSEMANATRABAJA',
       'F_ESTRATOVIVIENDA', 'F_TIENEINTERNET', 'F_EDUCACIONPADRE',
       'F_TIENELAVADORA', 'F_TIENEAUTOMOVIL', 'E_PRIVADO_LIBERTAD',
       'E_PAGOMATRICULAPROPIO', 'F_TIENECOMPUTADOR', 'F_TIENEINTERNET.1',
       'F_EDUCACIONMADRE', 'RENDIMIENTO_GLOBAL', 'INDICADOR_1', 'INDICADOR_2',
       'INDICADOR_3', 'INDICADOR_4'],
      dtype='object')

Resumen estadístico:
                   ID  PERIODO_ACADEMICO E_PRGM_ACADEMICO E_PRGM_DEPARTAMENTO  \
count   692500.000000      692500.000000           692500              692500
unique            NaN                NaN              948                  31
top               NaN                NaN          DERECHO              BOGOTÁ
freq              NaN                NaN            53244              282159
mean    494606.130576       20198.366679              NaN                 NaN
std     285585.209455          10.535037              NaN                 NaN
min          1.000000       20183.000000              NaN                 NaN
25%     247324.750000       20195.000000              NaN                 NaN
50%     494564.500000       20195.000000              NaN                 NaN
75%     741782.500000       20203.000000              NaN                 NaN
max     989286.000000       20213.000000              NaN                 NaN

                   E_VALORMATRICULAUNIVERSIDAD E_HORASSEMANATRABAJA  \
count                                   686213               661643
unique                                       8                    5
top     Entre 1 millón y menos de 2.5 millones      Más de 30 horas
freq                                    204048               249352
mean                                       NaN                  NaN
std                                        NaN                  NaN
min                                        NaN                  NaN
25%                                        NaN                  NaN
50%                                        NaN                  NaN
75%                                        NaN                  NaN
max                                        NaN                  NaN

       F_ESTRATOVIVIENDA F_TIENEINTERNET                    F_EDUCACIONPADRE  \
count             660363          665871                              669322
unique                 7               2                                  12
top            Estrato 2              Si  Secundaria (Bachillerato) completa
freq              232671          592514                              128289
mean                 NaN             NaN                                 NaN
std                  NaN             NaN                                 NaN
min                  NaN             NaN                                 NaN
25%                  NaN             NaN                                 NaN
50%                  NaN             NaN                                 NaN
75%                  NaN             NaN                                 NaN
max                  NaN             NaN                                 NaN

       F_TIENELAVADORA  ... E_PRIVADO_LIBERTAD E_PAGOMATRICULAPROPIO  \
count           652727  ...             692500                686002
unique               2  ...                  2                     2
top                 Si  ...                  N                    No
freq            563390  ...             692466                382201
mean               NaN  ...                NaN                   NaN
std                NaN  ...                NaN                   NaN
min                NaN  ...                NaN                   NaN
25%                NaN  ...                NaN                   NaN
50%                NaN  ...                NaN                   NaN
75%                NaN  ...                NaN                   NaN
max                NaN  ...                NaN                   NaN

       F_TIENECOMPUTADOR F_TIENEINTERNET.1  \
count             654397            665871
unique                 2                 2
top                   Si                Si
freq              597670            592514
mean                 NaN               NaN
std                  NaN               NaN
min                  NaN               NaN
25%                  NaN               NaN
50%                  NaN               NaN
75%                  NaN               NaN
max                  NaN               NaN

                          F_EDUCACIONMADRE RENDIMIENTO_GLOBAL    INDICADOR_1  \
count                               668836             692500  692500.000000
unique                                  12                  4            NaN
top     Secundaria (Bachillerato) completa               alto            NaN
freq                                141744             175619            NaN
mean                                   NaN                NaN       0.268629
std                                    NaN                NaN       0.122130
min                                    NaN                NaN       0.000000
25%                                    NaN                NaN       0.203000
50%                                    NaN                NaN       0.240000
75%                                    NaN                NaN       0.314000
max                                    NaN                NaN       0.657000

          INDICADOR_2    INDICADOR_3    INDICADOR_4
count   692500.000000  692500.000000  692500.000000
unique            NaN            NaN            NaN
top               NaN            NaN            NaN
freq              NaN            NaN            NaN
mean         0.259996       0.262087       0.262903
std          0.093480       0.058862       0.067944
min          0.000000       0.000000       0.000000
25%          0.212000       0.254000       0.255000
50%          0.271000       0.276000       0.285000
75%          0.309000       0.293000       0.303000
max          0.487000       0.320000       0.332000

[11 rows x 21 columns]